project:
  type: website
  output-dir: "."
  render:
    - index.qmd
    - "Lec_*.qmd"

website:
  title: "Elements of Sampling Survey"
  description: "Lecture slides"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false